Publish diagnostic
sbgisen/Azure_Kinect_ROS_Driver pull request #4
Opened 2024-12-25 08:04 UTC by Tacha-S

rgb_raw, depth_raw, ir_raw, imu, pointsに対してdiagnosticを出力するように

- fix #3

2024-12-26 07:27 UTC, jsupratman13 commented
@AiriYokochi @gakutasu @YS-KID @ChiroruNeko 

レビューしてみませんか？

2025-01-06 06:55 UTC, gakutasu reviewed
変更箇所でない部分で恐縮ですがtypo?があったのでコメントしました。

動作確認できる環境がなく、まだ動確できていませんが、実装は問題ないと思います。
さすがに動確してからマージすべきだと思うので、ほかの方にもレビューお願いしたいです。

2025-01-06 06:55 UTC, gakutasu commented on src/k4a_ros_device.cpp
>            result = getRbgFrame(capture, rgb_raw_frame);
`getRgbFrame`?

2025-01-08 00:05 UTC, Tacha-S commented
必要であれば自分のデスクの棚にAzure kinect置かれていると思うのでケーブルごと持っていってもらっても大丈夫です。

2025-01-14 09:04 UTC, Tacha-S commented
@sbgisen/researcher 誰か動作確認できますか？

2025-01-16 05:48 UTC, jsupratman13 requested changes

2025-01-16 05:48 UTC, jsupratman13 commented on src/k4a_ros_device.cpp
> +  updater_.setHardwareID("k4a");
`updater_.setHardwareID("k4a");` は diagnosed_pointcloud_publisher_, diagnosed_imu_publisher_の後で大丈夫？

2025-01-16 05:48 UTC, jsupratman13 commented on src/k4a_ros_device.cpp
> +  if (params_.depth_enabled)
XXX_enabled パラメータでトピック作るなら、 image_transportで作った**_publisherもこの条件分岐の下においたほうが見やすくなるのでは？

2025-01-16 05:48 UTC, jsupratman13 commented
> @sbgisen/researcher 誰か動作確認できますか？

動作確認しました。

2025-01-16 05:56 UTC, Tacha-S commented on src/k4a_ros_device.cpp
> +  updater_.setHardwareID("k4a");
問題ないです。

2025-01-16 05:58 UTC, Tacha-S commented on src/k4a_ros_device.cpp
> +  if (params_.depth_enabled)
そこまでazure kinectに未来を感じていないのでやりたければ自分でどうぞ

2025-01-16 06:18 UTC, jsupratman13 approved these changes

2025-01-16 06:19 UTC, jsupratman13 commented
@gakutasu 
もし問題なければマージしてください

2025-01-16 06:28 UTC, merged